src/fmf/apps/core/urls.py
from django.conf.urls.defaults import patterns, url
from views import IndexView, Test404, Test500, contacts, contanct_thank_you
from news.feeds import LatestNewsFeed

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index-view'),
    url(r'^rss/news/', LatestNewsFeed()),

    url(r'^404/$', Test404.as_view(), name='404'),
    url(r'^500/$', Test500.as_view(), name='500'),
    url(r'^contacts/$', contacts, name='contacts'),
    url(r'^contacts/thank_you/$', contanct_thank_you, name='contact-thank-you'),
)

src/fmf/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^localeurl/', include('localeurl.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/filebrowser/', include('filebrowser.urls')),
    url(r'^imperavi/', include('imperavi.urls')),

    url(r'^', include('core.urls')),
    url(r'^sections/', include('sections.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^feedbacks/', include('feedbacks.urls')),

)

if settings.DEBUG:
    urlpatterns += patterns("django.views",
        url(r"%s(?P<path>.*)$" % settings.STATIC_URL[1:], "static.serve", {
            "document_root": settings.STATIC_ROOT,
            'show_indexes': True,
        }),
        url(r"%s(?P<path>.*)$" % settings.MEDIA_URL[1:], "static.serve", {
            "document_root": settings.MEDIA_ROOT,
            'show_indexes': True,
        }),
    )


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

src/fmf/apps/core/models.py
from django.db import models
from django.template.base import Template
from django.template.context import Context
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from sections.models import Article, Section

from positions.fields import PositionField
from sorl.thumbnail.fields import ImageField
from sorl.thumbnail.helpers import ThumbnailError
from sorl.thumbnail.shortcuts import get_thumbnail


class IndexSliderImage(models.Model):

    page = models.OneToOneField(Article, verbose_name=_("Page"),
        unique=True, blank=True, null=True)
    section = models.OneToOneField(Section, verbose_name=_("Section"),
        unique=True, blank=True, null=True)
    custom_name = models.CharField(_("Custom name"), max_length=255)
    image = ImageField(_("Image"), upload_to='images/index/')
    position = PositionField()
    is_active = models.BooleanField(_("Active"), default=True)

    class Meta:
        ordering = ('position',)
        verbose_name = _("Image for slider")
        verbose_name_plural = _("Images for slider")

    def __unicode__(self):
        return _('Image for %s') % self.get_page_title

    def get_page_url(self):
        if self.section:
            return self.section.get_absolute_url()
        elif self.page:
            return self.page.get_absolute_url()

    @property
    def get_page_title(self):
        if self.section:
            return self.section.title
        elif self.page:
            return self.page.title
        else:
            return self.custom_name

    def thumb(self):
        try:
            im = get_thumbnail(self.image, '50x50', crop='center')
            t = Template('<img src="{{ image.url }}" alt="{{ alt }}" />')
            c = Context({"image": im, 'alt': self.page, })
            thum = t.render(c)
        except ThumbnailError:
            thum = _('No image')
        return  thum
    thumb.short_description = _('Image')
    thumb.allow_tags = True


def fill_empty_languages(instance, fields):
    empty_langs = dict()
    for field in fields:
        empty_langs[field] = list()
        for lang in settings.LANGUAGES:
            if not getattr(instance, '%s_%s' % (field, lang[0])):
                empty_langs[field].append(lang[0])
    #TODO make message in all languages
    text = "Content not avalible in this language."
    for field in fields:
        for lang in empty_langs[field]:
            setattr(instance, '%s_%s' % (field, lang), text)

src/fmf/apps/news/models.py
import uuid
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch.dispatcher import receiver
from django.template.base import Template
from django.template.context import Context
from django.utils.translation import ugettext_lazy as _

from sorl.thumbnail.fields import ImageField
from sorl.thumbnail.helpers import ThumbnailError
from sorl.thumbnail.shortcuts import get_thumbnail
from positions import PositionField

from core.models import fill_empty_languages


NEWS_CATEGORY_CHOICES = (
    ('dean', _("Dean")),
    ('first_year', _("First year")),
    ('fifth_year', _("Fifth year")),
)


class News(models.Model):
    title = models.CharField(_("Title"), max_length=256)
    slug = models.SlugField(_("Slug"), max_length=256)
    category = models.CharField(
        _("Category"), blank=True, null=True, max_length=255,
        choices=NEWS_CATEGORY_CHOICES
    )
    main_image = ImageField(upload_to='news/images', verbose_name=_("Main image"), blank=True, null=True)
    short_description = models.TextField(_("Short Description"))
    description = models.TextField(_("Description"))
    date = models.DateField(_("Date"), blank=True, null=True)
    position = PositionField(_("Position"), default=0)
    is_active = models.BooleanField(_("Active"), default=True)
    created = models.DateTimeField(_("Created"), auto_now_add=True, editable=False)

    class Meta:
        ordering = ('position',)
        verbose_name = _("News")
        verbose_name_plural = _("News")

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("news-detail", args=(self.slug,))

    def thumb(self):
        try:
            im = get_thumbnail(self.main_image, '50x50', crop='center')
            t = Template('<img src="{{ image.url }}" alt="{{ alt }}" />')
            c = Context({"image": im, 'alt': self.title})
            thum = t.render(c)
        except ThumbnailError:
            thum = _('No image')
        return  thum
    thumb.short_description = _('Image')
    thumb.allow_tags = True


@receiver(pre_save, sender=News)
def news_slug(sender, instance, **kwargs):
    if News.objects.exclude(pk=instance.pk).filter(slug=instance.slug):
        instance.slug += unicode(uuid.uuid4())[:5]


@receiver(pre_save, sender=News)
def news_empty_languages(sender, instance, **kwargs):
    fill_empty_languages(instance, ('description', 'short_description'))


class NewsImage(models.Model):
    news = models.ForeignKey(News, verbose_name=_("News"), related_name='images')
    title = models.CharField(_("Title"), max_length=256, blank=True, null=True)
    image = ImageField(upload_to='images/news/', verbose_name=_("Image"))
    position = PositionField(_("Position"), collection='news')

    class Meta:
        ordering = ('position',)
        verbose_name = _("Image")
        verbose_name_plural = _("Images")

    def __unicode__(self):
        if self.title:
            return _('image for %(news_title)s - %(title)s') % {'news_title':self.news.title, 'title':self.title}
        else:
            return _('image for %s') % self.news.title


class Event(models.Model):
    title = models.CharField(_("Title"), max_length=256)
    slug = models.SlugField(_("Slug"), max_length=256)
    date_from = models.DateField(_("Date from"), help_text=_("If date only one - put it just here"))
    date_to = models.DateField(_("Date to"), blank=True, null=True)
    image = ImageField(upload_to='images/events/', verbose_name=_("Main image"), blank=True, null=True)
    short_description = models.TextField(_("Short Description"))
    description = models.TextField(_("Description"))
    is_active = models.BooleanField(_("Active"), default=True)
    created = models.DateTimeField(_("Created"), auto_now_add=True, editable=False)

    class Meta:
        ordering = ('-date_to',)
        verbose_name = _("Event")
        verbose_name_plural = _("Events")

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("event-detail", args=(self.slug,))

    def thumb(self):
        try:
            im = get_thumbnail(self.image, '50x50', crop='center')
            t = Template('<img src="{{ image.url }}" alt="{{ alt }}" />')
            c = Context({"image": im, 'alt': self.title})
            thum = t.render(c)
        except ThumbnailError:
            thum = _('No image')
        return  thum
    thumb.short_description = _('Image')
    thumb.allow_tags = True


@receiver(pre_save, sender=Event)
def put_date_to(sender, instance, **kwargs):
    if not instance.date_to:
        instance.date_to = instance.date_from


@receiver(pre_save, sender=Event)
def events_empty_languages(sender, instance, **kwargs):
    fill_empty_languages(instance, ('description', 'short_description'))

src/fmf/apps/core/forms.py
from django import forms
from flatpages_my.models import FlatPage
from django.utils.translation import ugettext_lazy as _


class FlatpageForm(forms.ModelForm):

    url = forms.RegexField(label=_("URL"), max_length=100, regex=r'^[-\w/\.~]+$',
        help_text = _("Example: '/about/contact/'. Make sure to have leading"
                      " and trailing slashes."),
        error_message = _("This value must contain only letters, numbers,"
                          " dots, underscores, dashes, slashes or tildes."))

    class Meta:
        model = FlatPage


class ContactForm(forms.Form):
    email = forms.EmailField(label="", widget=forms.TextInput(attrs={
        'name':'email',
        'class':'validate[required,custom[email]]',
        'placeholder': _("Email"),
    }))
    name = forms.CharField(max_length=256, label="", widget=forms.TextInput(attrs={
        'class':'validate[required]',
        'placeholder': _("Name"),
    }))
    content = forms.CharField(max_length=2048, label="", widget=forms.Textarea(attrs={
        'class':'validate[required]',
        'placeholder': _("Message"),
    }))


class QuestionForm(forms.Form):
    answer = forms.ChoiceField(widget=forms.RadioSelect, choices=((1,1), (2,2), (3,3)))

src/fmf/apps/core/views.py
# -*- coding: utf-8 -*-
import logging
from django.core.mail import mail_managers
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.template.response import TemplateResponse
from django.utils import simplejson
from django.views.generic.base import TemplateView
from django.core.cache import cache

from models import IndexSliderImage
from forms import ContactForm
from news.models import News
from feedbacks.models import Feedback


logger = logging.getLogger("fmf.%s" % __name__)


class IndexView(TemplateView):
    template_name = 'core/index_view.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        images = cache.get('images', None)
        if not images:
            images = IndexSliderImage.objects.filter(is_active=True).select_related()
            cache.set('images', images)

        feedbacks = Feedback.objects.order_by('?').select_related()[:6]
        context.update({
            'images': images,
            'news_list': News.objects.filter(is_active=True).select_related(),
            'feedbacks': feedbacks,
        })
        return context


class Test404(TemplateView):
    template_name = '404.html'


class Test500(TemplateView):
    template_name = '500.html'


def contacts(request):
    form = ContactForm(request.POST or None)
    context = {
        'form': form,
    }
    if request.method == 'POST':
        if form.is_valid():
            #Mail managers
            subject = "Contact: %s (%s)" % (form.cleaned_data['name'], form.cleaned_data['email'])
            message = form.cleaned_data['content']
            html_message = render_to_string('contacts/manager_message.html', form.cleaned_data)
            mail_managers(subject, message, html_message=html_message)

            #TODO Mail person

            #Log to file
            logger.info('%s %s' % (subject, message))

            if request.is_ajax():
                response = render_to_string('contacts/ajax_response.html')
                response_dict = dict(content=response)
                return HttpResponse(simplejson.dumps(response_dict), mimetype='application/javascript')
            return redirect('contact-thank-you')
    return TemplateResponse(request, 'contacts/contacts.html', context)


def contanct_thank_you(request):
    return TemplateResponse(request, 'contacts/thank_you.html')

src/fmf/apps/core/templates/core/contacts.html
{% extends "base.html" %}

{% block content %}
  <div id="map_canvas" style="width:250px;height:250px;float:left;"></div>
  <div>
  {{ form.as_p }}
  </div>
{% endblock %}


{% block extra_js %}
  <script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>
  <script src="{{ STATIC_URL }}js/jquery.ui.map.min.js" type="text/javascript"></script>
  <script type="text/javascript">
    $(function() {
            // Also works with: var yourStartLatLng = '59.3426606750, 18.0736160278';
            var startLatLng = new google.maps.LatLng(59.3426606750, 18.0736160278);
            $('#map_canvas').gmap({'center': startLatLng});
    });
  </script>
{% endblock %}

src/fmf/apps/core/templates/core/index_view.html
{% extends "base.html" %}

{% load i18n thumbnail core_tags %}



{% block article %}

<!--left column-->
  <article id="left_column">

  {% block content %}
  <!--slider-->
    <section id="slider_box" class="bordered">
      <div id="slider">
        <ul>
          {% for image in images %}
            <li>
              {% thumbnail image.image '500x250' crop='center' as im %}
                <img src="{{ im.url }}" alt="{{ image.get_page_title }}">
              {% endthumbnail %}
              <div class="caption"><a href='{{ image.get_page_url|default:"#" }}'>{{ image.get_page_title }}</a></div>
            </li>
          {% endfor %}
        </ul>
      </div>
    </section>
    <!--end slider-->
  {% endblock %}

  </article>
<!--END left column-->

{% endblock %}

{% block aside_right %}

<!--right column-->
    <aside>
      <!--news-->
      <section id="news" class="bordered main_sect">
        <div class="title_arrow green">
          <h3 class="title_list">{% trans "Last news" %}:</h3>
          <p class="show_all"><a href="{% url news-list %}">{% trans "All" %} »</a></p>
        </div>
          <div class="tabbable tabs-below">
            <ul class="nav nav-tabs row-fluid">
              <li class="span3 active"><a href="#A" data-toggle="tab">{% trans "All news" %}</a></li>
              <li class="span3"><a href="#B" data-toggle="tab">{% trans "Dean" %}</a></li>
              <li class="span6 dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Admissions" %} <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#C" data-toggle="tab">{% trans "First year" %}</a></li>
                  <li><a href="#D" data-toggle="tab">{% trans "Fifth year" %}</a></li>
                </ul>
              </li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active streamer_slider" id="A">
                <ul>
                  {% for news in news_list|slice:"3" %}
                    <li class="img_descr">
                      <span class="date">{{ news.created|date:"d M. Y" }}</span>
                      {% if news.category %}
                        <a href="{% url news-list %}"><span class="label label-important fl-r">{{ news.get_category_display }}</span></a>
                      {% else %}
                        <a href="{% url news-list %}"><span class="label fl-r">{% trans "All" %}</span></a>
                      {% endif %}
                      <a class="news-title" href="{{ news.get_absolute_url }}">{{ news.title }}</a>
                    </li>
                  {% endfor %}
                </ul>
              </div>
              <div class="tab-pane streamer_slider" id="B">
                {% with news_list=news_list|from_category:'dean' %}
                  {% if news_list %}
                    <ul>
                      {% for news in news_list %}
                        <li class="img_descr">
                          <span class="date">{{ news.created|date:"d M. Y" }}</span>
                          <a class="news-title" href="{{ news.get_absolute_url }}">{{ news.title }}</a>
                        </li>
                      {% endfor %}
                    </ul>
                  {% else %}
                    <p>{% trans "No news in this category." %}</p>
                  {% endif %}
                {% endwith %}
              </div>
              <div class="tab-pane streamer_slider" id="C">
                {% with news_list=news_list|from_category:'first_year' %}
                  {% if news_list %}
                    <ul>
                      {% for news in news_list %}
                        <li class="img_descr">
                          <span class="date">{{ news.created|date:"d M. Y" }}</span>
                          <a class="news-title" href="{{ news.get_absolute_url }}">{{ news.title }}</a>
                        </li>
                      {% endfor %}
                    </ul>
                  {% else %}
                    <p>{% trans "No news in this category." %}</p>
                  {% endif %}
                {% endwith %}
              </div>
              <div class="tab-pane streamer_slider" id="D">
                {% with news_list=news_list|from_category:'fifth_year' %}
                  {% if news_list %}
                    <ul>
                      {% for news in news_list %}
                        <li class="img_descr">
                          <span class="date">{{ news.created|date:"d M. Y" }}</span>
                          <a class="news-title" href="{{ news.get_absolute_url }}">{{ news.title }}</a>
                        </li>
                      {% endfor %}
                    </ul>
                  {% else %}
                    <p>{% trans "No news in this category." %}</p>
                  {% endif %}
                {% endwith %}
              </div>
            </div>
          </div>
      </section>
      <!--end news-->
    </aside>

<!--END right column-->
{% endblock %}

{% block full_width %}
  <div class="container clearfix">
    <!--why_fmf?-->
    <section id="why_fmf" class="bordered main_sect">
      <div class="title_arrow blue">
        <h3 class="title_list">{% trans "Not so sure in future?" %}</h3>
      </div>
      <ul class="numbers-list row-fluid">
        <li class="first span4">
          <div class="numbers-box">
            <i class="icon-cogs fl-l"></i>
            <div class="description">
              <h3>{% trans "You are welcome!" %}</h3>
              <p><b>95%</b> {% trans "students on a budget" %};</p>
              <p><b>+ 20%</b> {% trans "to common studentship" %};</p>
              <p><b>36/60</b> {% trans "lowest passing score" %};</p>
              <p>{% trans "Have a question? Ask right" %} <a href="{% url contacts %}"><b>{% trans "here" %} »</b></a></p>
            </div>
          </div>
        </li>
        <li class="second span4">
          <div class="numbers-box">
            <i class="icon-book fl-l"></i>
            <div class="description">
              <h3>{% trans "Work hard!" %}</h3>
              <p><a href="http://fmf.kpi.ua/sections/pro-fakultet/spetsalnost/"><b>{% trans "The best" %}</b></a> {% trans "technical education in Ukraine" %};</p>
              <p><a href="http://fmf.kpi.ua/sections/spvprobtnitstvo/"><b>{% trans "Collaboration" %}</b></a> {% trans "with foreign universities" %};</p>
              <p>{% trans "Event full" %} <a href="http://studprofkom.kpi.ua/health"><b>{% trans "student life" %}</b></a></p>
            </div>
          </div>
        </li>
        <li class="third span4">
          <div class="numbers-box">
            <i class="icon-thumbs-up fl-l"></i>
            <div class="description">
              <h3>{% trans "Become successful" %}!</h3>
              <p>{% trans "It goes without saying." %}<br/>
                {% trans "Our progress:" %}</p>
            </div>
          </div>
          <i class="icon-arrow-down"></i>
        </li>
      </ul>
      <div class="row-fluid feedbacks">
        <div class="span7">
          <div class="feedback-main">
            <div class="feedback-image-main span6" id="feedback-image-main"></div>
            <div id="feedback-description-main" class="span6"></div>
          </div>
        </div>
        <div class="span5">
          <!-- feefbacks -->
          <ul class="feedback thumbnails">
            {% for feedback in feedbacks %}
              <li class="{% if forloop.first %}feedback-active{% else %}feedback{% endif %}">
                <a class="thumbnail" href="#">
                  {% thumbnail feedback.image "95x100" crop="top" as im %}
                    <img src="{{ im.url }}" alt="{{ feedback.name }}">
                  {% endthumbnail %}
                </a>
                <div class="feedback-name" style="display:none;">{{ feedback.name }}</div>
                <div class="feedback-short-description" style="display:none;">{{ feedback.short_description|safe }}</div>
                <div class="feedback-image" style="display:none;">
                  <a href="{% if feedback.content %}{{ feedback.get_absolute_url }}{% else %}#{% endif %}">
                  {% thumbnail feedback.image "220x240" crop="top" as im %}
                    <img src="{{ im.url }}" alt="{{ feedback.name }}">
                  {% endthumbnail %}
                  </a>
                </div>
                <div class="feedback-description" style="display:none;">
                  <div class="name"><span>{{ feedback.name }}</span></div>
                  <p>{{ feedback.description|safe }}</p>
                  {% if feedback.content %}<a class="feedback-description-link" href="{{ feedback.get_absolute_url }}">{% trans "Interview" %} »</a>{% endif %}
                </div>
              </li>
            {% endfor %}
          </ul>
          <p class="feedbacks-all-link"><a href="{% url feedback-list %}">{% trans "All" %} »</a></p>
          <!-- EO feefbacks -->
        </div>
      </div>
    </section>
  </div>
{% endblock %}

{% block extra_js %}
  <script src="{{ STATIC_URL }}js/jquery.sudoSlider.js"></script>
  <script src="{{ STATIC_URL }}js/bootstrap/bootstrap.min.js"></script>
  <script type="text/javascript">
      // Popovers on feedback previews
      $('.feedback a').each(function(){
          var title = $(this).next('.feedback-name').text();
          var content = $(this).siblings('.feedback-short-description').text();
          $(this).popover({
              'placement': 'top',
              'title': title,
              'content': content
          });
      });
  </script>
{% endblock %}

src/fmf/apps/core/templates/core/nav.html
{% load i18n chunks cache %}

<ul>
  {% for section in sections %}
    <li {% ifequal active section.slug %}class="active"{% endifequal %}><a href="{{ section.get_absolute_url }}">{{ section }}</a>
      <ul>
        {% for article in section.articles.all %}
          <li><a href="{{ article.get_absolute_url }}">{{ article }}</a></li>
        {% endfor %}
      </ul>
    </li>
  {% endfor %}
</ul>

src/fmf/apps/core/templates/core/question.html
{% extends "base.html" %}

{% block content %}
{#  {% if result %}#}
{#    {{ result }}#}
{#  {% else %}#}
      <p>Скільки буде 1+1?</p>
{#      <form action="." method="post">{% csrf_token %}#}
{#        {{ question_form }}#}
{#        <input type="submit" value="Send">#}
{#      </form>#}
{#  {% endif %}#}

  <form action=".">
    <ul>
      <li><label for="id_answer_0"><input type="radio" id="id_answer_0" value="1" name="answer"> 1</label></li>
      <li><label for="id_answer_1"><input type="radio" id="id_answer_1" value="2" name="answer"> 2</label></li>
      <li><label for="id_answer_2"><input type="radio" id="id_answer_2" value="3" name="answer"> 3</label></li>
    </ul>
  </form>
{% endblock %}

{% block extra_js %}
  <script type="text/javascript">
    $('input').click(function(){
      if ($(this).val()==2) {
        $(this).parents('form').html('DONE');
      }
      else {
        $(this).parents('label').replaceWith('wrong');
      }
    })

  </script>
{% endblock %}